### PR TITLE
added simple Tests

### PR DESCRIPTION
**Pull request by Ksengine**
created github action amed `ci`
- check code style with flake8
- test with pytest

### CODE REVIEW

**Comment by qweeze** [comment]
Thanks for the PR!

This project isn't meant to be actively developed, it's basically a tutorial on how ASGI works, so I don't think we need an automated CI here. Also the idea was to keep it minimal and dependency-free, adding linters or test frameworks would break that

**Comment by Ksengine** [comment]
I like to develop it. Please pass methe ownership(if you like)

**Comment by qweeze** [comment]
This project is just an example, so there's nothing to develop here. If you want to create a full-featured framework based on this code, you can fork it

**Comment by Ksengine** [comment]
I like to publish it as `nanoasgi`?

**Comment by qweeze** [comment]
Well, if you will develop it it won't be `nano` anymore ;)

**Comment by Ksengine** [comment]
Can I use the name nanoasgi

**Comment by qweeze** [comment]
Yes

**Pull request closed without merging**
